<ul id="right_sub_navigaion" role="navigation">
  <?php if($active_page == 'main'): ?>
  <li class="select">Attribute</li>
  <?php else: ?>
  <li><a href="<?php echo $basePath; ?>/<?php echo $adminAreaToken; ?>/attribute/index">Attribute</a></li>
  <?php endif; ?>
  <?php if($this->active_page == 'add'): ?>
  <li class="select">Add Attribute group</li>
  <?php else: ?>
  <li><a href="<?php echo $basePath; ?>/<?php echo $adminAreaToken; ?>/attribute-group-add/index">Add Attribute group</a></li>
  <?php endif; ?>
</ul>
