<?php if (($this->pageCount) && ($this->pageCount > 1)): ?>

<div class="paginationControl">

<!-- Previous page link -->

<?php if (isset($this->previous)): ?>

  <a href="<?php echo $this->url('admin'); ?>/item-search/search/item/<?php echo $this->item; ?>/page/<?php echo $this->previous; ?>/callback_num/<?php echo $this->callback_num; ?>">&lt; Previous</a> |


<?php else: ?>

  <span class="disabled">&lt; Previous</span> |

<?php endif; ?>

<!-- Numbered page links -->

<?php foreach ($this->pagesInRange as $page): ?>

  <?php if ($page != $this->current): ?>
  
    <a href="<?php echo $this->url('admin'); ?>/item-search/search/item/<?php echo $this->item; ?>/page/<?php echo $page; ?>/callback_num/<?php echo $this->callback_num; ?>"><?php echo $page; ?></a> |

  <?php else: ?>

    <?php echo $page; ?> |

  <?php endif; ?>

<?php endforeach; ?>

 

<!-- Next page link -->

<?php if (isset($this->next)): ?>

  <a href="<?php echo $this->url('admin'); ?>/item-search/search/item/<?php echo $this->item; ?>/page/<?php echo $this->next; ?>/callback_num/<?php echo $this->callback_num; ?>">Next &gt;</a>

<?php else: ?>

  <span class="disabled">Next &gt;</span>

<?php endif; ?>

</div>

<?php endif; ?>