<div class="subcolumns">
  <div class="c75l">

    <h1 id="page_head">Add new attribute to group: <?php echo $escape->escapeHtml($attribute_group_name); ?></h1>

    <div>&nbsp;</div>

    <?php if(count($error) > 0): ?>
    <div id="error" aria-live="rude">
        <h2>Error:</h2>
        <?php foreach($error as $error): ?>
            <h3><?php echo $escape->escapeHtml($error); ?></h3>
        <?php endforeach; ?>
    </div>
    <?php endif; ?>

    <form name="setup" id="setup" method="post" action="<?php echo $basePath; ?>/<?php echo $adminAreaToken; ?>/attribute-add/add" accept-charset="utf-8">
    <input type="hidden" name="id_group" value="<?php echo $escape->escapeHtmlAttr($id_group); ?>" />
        <ul class="ul-form" role="slider">
            <li class="item_label"><h2><label for="attribute_name" id="an">Attribute name:</label></h2></li>
            <li class="item_content">
                    <input aria-required="true"
                           aria-labelledby="agn"
                           name="attribute_name"
                           id="attribute_name"
                           tabindex="1"
                           type="text"
                           size="40"
                           maxlength="126"
                           value="<?php echo $escape->escapeHtmlAttr($attribute_name); ?>" />
            </li>

            <li class="item_label"><h2><label for="attribute_title" id="atit">Attribute title:</label></h2></li>
            <li class="item_content">
                    <input aria-required="true"
                           aria-labelledby="atit"
                           name="attribute_title"
                           id="attribute_title"
                           tabindex="2"
                           type="text"
                           size="40"
                           maxlength="126"
                           value="<?php echo $escape->escapeHtmlAttr($attribute_title); ?>" />
            </li>

            <li class="item_label"><h2><label for="attribute_type" id="at">Attribute type:</label></h2></li>
            <li class="item_content">
                            <select name="attribute_type" id="attribute_type" size="1" tabindex="3">
                            <option value="bool"<?php if(strcasecmp($attribute_type, 'bool')==0): ?> selected="selected" class="selected"<?php endif; ?>>boolean&nbsp;&nbsp;</option>
                            <option value="int"<?php if(strcasecmp($attribute_type, 'int')==0): ?> selected="selected" class="selected"<?php endif; ?>>integer&nbsp;&nbsp;</option>
                            <option value="float"<?php if(strcasecmp($attribute_type, 'float')==0): ?> selected="selected" class="selected"<?php endif; ?>>float&nbsp;&nbsp;</option>
                            <option value="string"<?php if(strcasecmp($attribute_type, 'string')==0): ?> selected="selected" class="selected"<?php endif; ?>>string&nbsp;&nbsp;</option>
                            </select>
            </li>

            <li class="item_label"><h2><label for="attribute_regex" id="mv">Is multi value:</label></h2></li>
            <li class="item_content">
                    <input aria-labelledby="mv"
                           name="multi_value"
                           id="multi_value"
                           tabindex="4"
                           type="checkbox"
                           <?php if('1' == $multi_value): ?>checked="checked"<?php endif; ?>
                           value="1" />
            </li>

            <li class="item_label"><h2><label for="attribute_default_value" id="adv">Attribute unit:</label></h2></li>
            <li class="item_content">
                    <input aria-labelledby="adv"
                           name="attribute_unit"
                           id="attribute_unit"
                           tabindex="5"
                           type="text"
                           size="40"
                           maxlength="126"
                           value="<?php echo $escape->escapeHtmlAttr($attribute_unit); ?>" />
            </li>

            <li class="item_label"><h2><label for="attribute_regex" id="ar">Attribute regex:</label></h2></li>
            <li class="item_content">
                    <input aria-labelledby="ar"
                           name="attribute_regex"
                           id="attribute_regex"
                           tabindex="6"
                           type="text"
                           size="40"
                           maxlength="1000"
                           value="<?php echo $escape->escapeHtmlAttr($attribute_regex); ?>" />
            </li>

            <li class="item_label"><h2><label for="attribute_regex" id="dd">Default display:</label></h2></li>
            <li class="item_content">
                    <input aria-labelledby="dd"
                           name="default_display"
                           id="default_display"
                           tabindex="7"
                           type="checkbox"
                           <?php if('1' == $default_display): ?>checked="checked"<?php endif; ?>
                           value="1" />
            </li>

            <li class="item_label"><h2><label for="attribute_description" id="ad">Attribute group description:</label></h2></li>
            <li class="item_content">
                    <textarea name="attribute_description"
                              id="attribute_description"
                              aria-labelledby="ad"
                              tabindex="8"
                              cols="50"
                              rows="5"><?php echo $escape->escapeHtml($attribute_description); ?></textarea>
            </li>

            <li class="item_label"><h2><label for="submit" id="sub">Submit new attribute or cancel:</label></h2></li>
            <li class="item_content">
                <input role="button"
                       aria-labelledby="sub"
                       tabindex="9"
                       type="submit"
                       name="add"
                       id="submit"
                       value="Submit" />

                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

                <input role="button"
                       tabindex="10"
                       aria-labelledby="sub"
                       type="submit"
                       name="cancel"
                       id="cancel"
                       value="Cancel" />
            </li>
        </ul>

    </form>

  </div>

  <div class="c25r right_navigation">
      <?php $partialData['basePath'] = $basePath; $partialData['adminAreaToken'] = $adminAreaToken; ?>
      
      <?php echo $this->partial('layout/_attribute_group_navigation.phtml', 
                                $partialData); ?>
  </div>
</div>