<div class="subcolumns">
  <div class="c75l">

    <h1 id="page_head">Context</h1>

    <ul id="node-branch" role="navigation" title="context branch">
    <li><a href="<?php echo $basePath; ?>/<?php echo $adminAreaToken; ?>/context/index/id_context/0">Root</a>/</li>
    <?php foreach( $context_branch_result as $branch): ?>
        <li><a href="<?php echo $basePath; ?>/<?php echo $adminAreaToken; ?>/context/index/id_context/<?php  echo $branch['id_context']; ?>"><?php  echo $branch['title']; ?></a>/</li>
    <?php endforeach; ?>
    </ul>

    <div class="separation">&nbsp;</div>

    <?php if(count($context_result) > 0): ?>
 
    <ul id="node-list">
    
    <?php foreach( $context_result as $context): ?>
        <li <?php if($context['id_status']==0): ?>
            class="status-trash" title="trash"
            <?php elseif($context['id_status']==100): ?>
            class="status-inactive" title="inactive"
            <?php elseif($context['id_status']==200): ?>
            class="status-active" title="active"
            <?php endif; ?>><a href="<?php echo $basePath; ?>/<?php echo $adminAreaToken; ?>/context/index/id_context/<?php  echo $context['id_context']; ?>"><?php  echo $context['title']; ?></a> 
            <span class="additional-link-info">(<abbr title="Number of child contexts"><?php  echo $context['num_childs']; ?></abbr>)
            <?php if($context['system_serial'] != NULL): ?>
            <a href="<?php echo $basePath; ?>/<?php echo $adminAreaToken; ?>/context-edit/index/id_context/<?php  echo $context['id_context']; ?>">edit</a>
            <?php endif; ?>
            </span></li>
    <?php endforeach; ?>
    </ul>

    <?php endif; ?>

  </div>
  <div class="c25r right_navigation">
      <?php $partialData['basePath'] = $basePath; $partialData['adminAreaToken'] = $adminAreaToken; ?>

      <?php echo $this->partial('layout/_context_navigation.phtml', 
                                $partialData); ?>
  </div>
</div>


